"""Build release archives and publish complete, retryable GitHub releases,
the crates, and the Homebrew formula."""

import argparse
import base64
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tarfile
import tomllib
from urllib.error import HTTPError
from urllib.parse import quote
from urllib.request import Request, urlopen
import zipfile


# Linux binaries link musl statically so they run on any distribution.
TARGETS = {
    "x86_64-unknown-linux-musl": "linux-amd64",
    "aarch64-unknown-linux-musl": "linux-arm64",
    "x86_64-apple-darwin": "macos-amd64",
    "aarch64-apple-darwin": "macos-arm64",
    "x86_64-pc-windows-msvc": "windows-amd64",
    "aarch64-pc-windows-msvc": "windows-arm64",
}

# Publication order: the CLI depends on the library.
PACKAGES = ("squeeze-core", "squeeze-cli")

FORMULA = """\
# frozen_string_literal: true

# Generated by squeeze's release workflow; do not edit.
class Squeeze < Formula
  desc "Extract URLs, emails, IPs, hashes, TODOs, and more from any text"
  homepage "https://github.com/{repository}"
  version "{version}"
  license "MIT"

{platforms}
  conflicts_with "squeeze-nightly", because: "squeeze-nightly and squeeze install the same binary"

  def install
    bin.install "squeeze"
    generate_completions_from_executable(bin/"squeeze", "--completions")
  end

  test do
    output = pipe_output("#{{bin}}/squeeze --url", "visit https://example.com today")
    assert_equal "https://example.com", output.strip
  end
end
"""


def api(method, path, data=None, allow_missing=False, content_type="application/json"):
    url = path if path.startswith("https://") else "https://api.github.com" + path
    payload = json.dumps(data).encode() if isinstance(data, dict) else data
    request = Request(url, data=payload, method=method, headers={
        "Authorization": "Bearer " + os.environ.get("GH_TOKEN", ""),
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": content_type,
    })
    try:
        with urlopen(request, timeout=120) as response:
            body = response.read()
            return json.loads(body) if body else None
    except HTTPError as error:
        if allow_missing and error.code == 404:
            return None
        raise


def endpoint(path):
    return f"/repos/{os.environ['GITHUB_REPOSITORY']}/{path}"


def output(name, value):
    with open(os.environ["GITHUB_OUTPUT"], "a") as stream:
        print(f"{name}={value}", file=stream)


def crate_version(root=Path(".")):
    manifests = {}
    for crate in ("squeeze", "squeeze-cli"):
        with (root / crate / "Cargo.toml").open("rb") as stream:
            manifests[crate] = tomllib.load(stream)
    versions = [manifest["package"]["version"] for manifest in manifests.values()]
    required = manifests["squeeze-cli"].get("dependencies", {}).get("squeeze", {}).get("version")
    if len(set(versions)) != 1 or required not in (None, versions[0]):
        raise ValueError(f"Crate versions differ: {versions}, CLI requires {required}")
    if not re.fullmatch(r"\d+\.\d+\.\d+", versions[0]):
        raise ValueError("Automatic releases require a stable major.minor.patch version")
    return versions[0]


def validate_tag(version, ref_type, ref_name):
    tag = "v" + version
    if ref_type == "tag" and ref_name != tag:
        raise ValueError(f"Tag {ref_name} does not match crate version {version}")
    if ref_type != "tag" and ref_name != "main":
        raise ValueError("Releases must run from main or a version tag")
    return tag


def tag_commit(tag):
    ref = api("GET", endpoint(f"git/ref/tags/{tag}"), allow_missing=True)
    if ref is None:
        return None
    target = ref["object"]
    while target["type"] == "tag":
        target = api("GET", endpoint(f"git/tags/{target['sha']}"))["object"]
    if target["type"] != "commit":
        raise ValueError(f"Tag {tag} does not point to a commit")
    return target["sha"]


def ensure_tag(tag, sha, create):
    existing = tag_commit(tag)
    if existing is None:
        if create:
            api("POST", endpoint("git/refs"), {"ref": f"refs/tags/{tag}", "sha": sha})
        return
    if existing != sha:
        raise ValueError(f"Existing tag {tag} points to a different commit")


def prepare():
    version = crate_version()
    tag = validate_tag(version, os.environ.get("GITHUB_REF_TYPE", "branch"),
                       os.environ.get("GITHUB_REF_NAME", "main"))
    output("version", version)
    output("tag", tag)
    unpublished = unpublished_crates(version)
    if unpublished and os.environ.get("HAS_CRATES_TOKEN") != "true":
        print(f"::notice::Set CARGO_REGISTRY_TOKEN to publish {', '.join(unpublished)} {version}")
        unpublished = []
    output("publish_crates", "true" if unpublished else "false")
    existing = api("GET", endpoint(f"releases/tags/{tag}"), allow_missing=True)
    if existing is not None and not existing["draft"]:
        output("should_release", "false")
        if unpublished:
            # Crates published after the release must come from the tagged commit.
            output("sha", tag_commit(tag))
        print(f"{tag} is already published")
        return
    sha = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    ensure_tag(tag, sha, create=False)
    output("sha", sha)
    output("should_release", "true")


def archive_name(tag, target):
    suffix = "zip" if "windows" in target else "tar.gz"
    return f"squeeze-{tag}-{TARGETS[target]}.{suffix}"


def package(tag, target, root=Path(".")):
    binary = "squeeze.exe" if "windows" in target else "squeeze"
    files = [(root / "target" / target / "release" / binary, binary),
             (root / "LICENSE", "LICENSE"), (root / "readme.md", "readme.md")]
    destination = root / "dist" / archive_name(tag, target)
    destination.parent.mkdir(exist_ok=True)
    if "windows" in target:
        with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            for path, name in files:
                archive.write(path, name)
    else:
        with tarfile.open(destination, "w:gz") as archive:
            for path, name in files:
                archive.add(path, arcname=name)
    return destination


def publish(tag, sha):
    expected = {archive_name(tag, target) for target in TARGETS}
    archives = sorted(path for path in Path("dist").iterdir() if path.name != "SHA256SUMS")
    if {path.name for path in archives} != expected:
        raise ValueError("Release requires exactly the six platform archives")
    checksums = Path("dist/SHA256SUMS")
    checksums.write_text("".join(
        f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.name}\n" for path in archives
    ))
    ensure_tag(tag, sha, create=True)
    existing = api("GET", endpoint(f"releases/tags/{tag}"), allow_missing=True)
    if existing is not None and not existing["draft"]:
        raise ValueError(f"{tag} was published while building; refusing to replace its assets")
    if existing is None:
        existing = api("POST", endpoint("releases"), {
            "tag_name": tag, "target_commitish": sha, "name": tag,
            "draft": True, "generate_release_notes": True,
        })
    release_path = endpoint(f"releases/{existing['id']}")
    assets = api("GET", release_path + "/assets?per_page=100")
    for asset in assets:
        api("DELETE", endpoint(f"releases/assets/{asset['id']}"))
    upload_url = existing["upload_url"].split("{", 1)[0]
    for path in archives + [checksums]:
        api("POST", upload_url + "?name=" + quote(path.name), path.read_bytes(),
            content_type="application/octet-stream")
    api("PATCH", release_path, {"draft": False, "make_latest": "true"})


def crate_published(name, version):
    request = Request(f"https://crates.io/api/v1/crates/{name}/{version}", headers={
        "User-Agent": "squeeze-release (https://github.com/aymericbeaumet/squeeze)",
    })
    try:
        with urlopen(request, timeout=60):
            return True
    except HTTPError as error:
        if error.code == 404:
            return False
        raise


def unpublished_crates(version):
    # crates.io being unreachable must not hold back the binary release; the
    # crates job checks again before publishing.
    try:
        return [name for name in PACKAGES if not crate_published(name, version)]
    except OSError as error:
        print(f"::warning::Could not query crates.io ({error}); the crates job will check again")
        return list(PACKAGES)


def publish_crates(version):
    for name in PACKAGES:
        if crate_published(name, version):
            print(f"{name} {version} is already on crates.io")
            continue
        # Cargo waits for each crate to reach the index before publishing its dependents.
        subprocess.run(["cargo", "publish", "--locked", "--package", name], check=True)


def homebrew_formula(tag, checksums):
    repository = os.environ["GITHUB_REPOSITORY"]
    platforms = []
    for os_block, os_name in (("on_macos", "macos"), ("on_linux", "linux")):
        arches = []
        for arch_block, arch in (("on_arm", "arm64"), ("on_intel", "amd64")):
            name = f"squeeze-{tag}-{os_name}-{arch}.tar.gz"
            arches.append(
                f"    {arch_block} do\n"
                f'      url "https://github.com/{repository}/releases/download/{tag}/{name}"\n'
                f'      sha256 "{checksums[name]}"\n'
                "    end\n"
            )
        platforms.append(f"  {os_block} do\n" + "".join(arches) + "  end\n")
    return FORMULA.format(repository=repository, version=tag.removeprefix("v"),
                          platforms="\n".join(platforms))


def update_homebrew(tag, tap):
    url = f"https://github.com/{os.environ['GITHUB_REPOSITORY']}/releases/download/{tag}/SHA256SUMS"
    with urlopen(url, timeout=120) as response:
        checksums = {name: digest for digest, name in
                     (line.split() for line in response.read().decode().splitlines())}
    formula = homebrew_formula(tag, checksums)
    path = f"/repos/{tap}/contents/Formula/squeeze.rb"
    current = api("GET", path, allow_missing=True)
    if current is not None and base64.b64decode(current["content"]).decode() == formula:
        print(f"{tap} already installs {tag}")
        return
    body = {"message": f"chore: update squeeze to {tag.removeprefix('v')}",
            "content": base64.b64encode(formula.encode()).decode()}
    if current is not None:
        body["sha"] = current["sha"]
    api("PUT", path, body)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("prepare", "package", "publish", "crates", "homebrew"))
    parser.add_argument("--tag")
    parser.add_argument("--target", choices=TARGETS)
    parser.add_argument("--sha")
    parser.add_argument("--tap")
    args = parser.parse_args()
    if args.command == "prepare":
        prepare()
    elif args.command == "package":
        package(args.tag, args.target)
    elif args.command == "publish":
        publish(args.tag, args.sha)
    elif args.command == "crates":
        publish_crates(crate_version())
    else:
        update_homebrew(args.tag, args.tap)
