# Link the C runtime statically so the Windows binaries run without the
# Visual C++ Redistributable.
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
