#!/usr/bin/env python3
"""Regenerate squeeze/iana.rs from the IANA TLD and URI scheme registries."""

import csv
import datetime
import io
import pathlib
import urllib.request

TLDS_URL = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt"
SCHEMES_URL = "https://www.iana.org/assignments/uri-schemes/uri-schemes-1.csv"
OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "squeeze" / "iana.rs"
WIDTH = 96


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "squeeze-update-iana"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode()


def parse_tlds(text):
    header, *lines = text.splitlines()
    # "# Version 2026092300, Last Updated ..."
    version = header.split()[2].rstrip(",")
    names = {line.strip().lower() for line in lines if line.strip()}
    return version, sorted(name for name in names if not name.startswith("xn--"))


def parse_schemes(text):
    rows = csv.DictReader(io.StringIO(text))
    return sorted(
        {
            row["URI Scheme"].lower()
            for row in rows
            # Annotated entries such as "shttp (OBSOLETE)" are retired.
            if row["Status"].lower() in ("permanent", "provisional")
            and " " not in row["URI Scheme"]
        }
    )


def phf_set(name, items):
    lines, line = [], "   "
    for item in items:
        entry = f' "{item}",'
        if len(line) + len(entry) > WIDTH:
            lines.append(line)
            line = "   "
        line += entry
    lines.append(line)
    body = "\n".join(lines)
    return f"pub(crate) static {name}: phf::Set<&'static str> = phf::phf_set! {{\n{body}\n}};\n"


def main():
    version, tlds = parse_tlds(fetch(TLDS_URL))
    schemes = parse_schemes(fetch(SCHEMES_URL))
    today = datetime.date.today().isoformat()
    OUTPUT.write_text(
        "//! IANA registries embedded for match validation. Generated by\n"
        "//! `scripts/update_iana.py` (`mise run update-iana`); do not edit.\n"
        "//!\n"
        f"//! - `TLDS`: <{TLDS_URL}>\n"
        f"//!   (version {version}), lowercased, without `xn--` labels.\n"
        f"//! - `URI_SCHEMES`: <{SCHEMES_URL}>\n"
        f"//!   (retrieved {today}), lowercased, permanent and provisional only.\n"
        "\n" + phf_set("TLDS", tlds) + "\n" + phf_set("URI_SCHEMES", schemes)
    )
    print(f"wrote {OUTPUT}: {len(tlds)} TLDs, {len(schemes)} URI schemes")


if __name__ == "__main__":
    main()
