[package]
name = "squeeze-cli"
version = "0.1.0"
authors = ["Aymeric Beaumet <hi@aymericbeaumet.com>"]
edition = "2018"

[[bin]]
name = "squeeze"
path = "main.rs"

[dependencies]
clap = "3.0.0-beta.2"
log = "0.4.11"
pretty_env_logger = "0.4.0"
squeeze = { path = "../squeeze" }
